version: "3"
services:
  stream9php81:
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $OS9
  stream9php81reloc:
    command: ["-ba", "--with", "relocation"]
    volumes:
      - rpm9stream:/home/centos/rpmbuild/RPMS
    build:
      context: .
      args:
        os: $OS9

volumes:
  rpm9stream:
    name: rpm9stream
