services:
  rocky8base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        os: $RL8
    image: "aursu/php82build:${RL8TAG}-base"
  rocky9base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        os: $RL9
    image: "aursu/php82build:${RL9TAG}-base"
  stream9base:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        os: $OS9
    image: "aursu/php82build:${OS9TAG}-base"
