version: "3"
services:
  centos7php81dev:
    build:
      context: dev
      args:
        os: $OS7
    image: "aursu/php81build:${OS7TAG}-dev"
  rocky8php81dev:
    build:
      context: dev
      args:
        os: $RL8
    image: "aursu/php81build:${RL8TAG}-dev"
  stream9php81dev:
    build:
      context: dev
      args:
        os: $OS9
    image: "aursu/php81build:${OS9TAG}-dev"
  centos7php81dev2:
    build:
      context: dev
      args:
        os: $OS7
        image: dev2base
    image: "aursu/php81build:${OS7TAG}-dev2"
  rocky8php81dev2:
    build:
      context: dev
      args:
        os: $RL8
        image: dev2base
    image: "aursu/php81build:${RL8TAG}-dev2"
  stream9php81dev2:
    build:
      context: dev
      args:
        os: $OS9
        image: dev2base
    image: "aursu/php81build:${OS9TAG}-dev2"